version: "3.0"
services: 
  db:
    image: mysql:8
    environment: 
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_USER: root
      MYSQL_PASSWORD: 1234
      MYSQL_DATABASE: whynot
    ports: 
      - 3306:3306
  service-a:
    build: .
    restart: on-failure
    links: 
      - db
    depends_on: 
      - db

