server:
  port: 443
  ssl:
    enabled: true
    enabled-protocols:
      - TLSv1.1
      - TLSv1.2
    key-store: classpath:whynot-config/apple-oauth-keys/keystore.p12
    key-store-type: PKCS12
    key-store-password: 1234
  error:
    include-stacktrace: never
  servlet:
    session:
      cookie:
        same-site: NONE
        http-only: true

spring:
  security:
    oauth2:
      redirect-uri: http://localhost:3000
      information-uri-essential: http://localhost:4000 # todo: 안내페이지 주소 나오면 변경
      information-uri-email: http://localhost:4000 # todo: 안내페이지 주소 나오면 변경
      client:
        registration:
          google:
            client-id: ${google.client.id}
            client-secret: ${google.client.secret}
            scope: ${google.client.scope}
          naver:
            client-id: ${naver.client.id}
            client-secret: ${naver.client.secret}
            redirect_uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            scope: ${naver.client.scope}
            client-name: Naver
          kakao:
            client-id: ${kakao.client.id}
            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            scope: ${kakao.client.scope}
            client-name: Kakao
          apple:
            client-name: apple
            client-id: ${apple.aud}
            client-secret: ${apple.key.id}
            client-authentication-method: POST
            redirect-uri: "{baseUrl}/v2/login/apple"
            authorization-grant-type: authorization_code
            scope: ${apple.scope}
            issuer: ${apple.iss}
            audience: ${apple.aud}
            team-id: ${apple.team.id}
            key-id: ${apple.key.id}
            key-path: ${apple.key.path}
            redirect-url: ${apple.redirectUrl}
        provider:
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response
          kakao:
            authorization_uri: https://kauth.kakao.com/oauth/authorize
            token_uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user_name_attribute: id
          apple:
            authorization-uri: https://appleid.apple.com/auth/authorize?response_mode=form_post
            token-uri: https://appleid.apple.com/auth/token
            jwk-set-uri: https://appleid.apple.com/auth/keys

  config:
    import: classpath:/whynot-config/env-local.yml
    activate:
      on-profile: "local"

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${db.url}/whynot?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: ${db.username}
    password: ${db.password}

  jpa:
    generate-ddl: true
    database: MYSQL
    showSql: true
    hibernate:
      ddl-auto: none
    properties.hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
      format_sql: true
      show_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${mail.sender.name}
    password: ${mail.sender.password}
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

cloud:
  aws:
    credentials:
      accessKey: ${aws.s3.accessKey}
      secretKey: ${aws.s3.secretKey}
    s3:
      bucket: ${aws.s3.bucketName}
    region:
      static: ${aws.s3.staticName}
    stack:
      auto: false

jwt:
  secretKey: ${jwt.token.secret}
  expiredTime:
    access-token: 10000
    refresh-token: 20000

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

logging:
  config: 'classpath:logback-spring-local.xml'
  level:
    root: INFO
    com.amazonaws.util.EC2MetadataUtils: error