server:
  port: 9000
  error:
    include-stacktrace: never
  servlet:
    session:
      cookie:
        same-site: NONE
        http-only: true

spring:
  config:
    import: classpath:/whynot-config/env-local.yml
    activate:
      on-profile: "local"

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${db.url}/whynot?characterEncoding=UTF-8&serverTimezone=UTC
    username: ${db.username}
    password: ${db.password}

  jpa:
    generate-ddl: true
    database: MYSQL
    showSql: true
    hibernate:
      ddl-auto: none
    properties.hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
      format_sql: true
      show_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${mail.sender.name}
    password: ${mail.sender.password}
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true

  servlet:
    multipart:
      max-file-size: 3MB
      max-request-size: 3MB

cloud:
  aws:
    credentials:
      accessKey: ${aws.s3.accessKey}
      secretKey: ${aws.s3.secretKey}
    s3:
      bucket: ${aws.s3.bucketName}
    region:
      static: ${aws.s3.staticName}
    stack:
      auto: false

jwt:
  secretKey: ${jwt.token.secret}
  expiredTime:
    access-token: 30
    refresh-token: 300

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

logging:
  config: 'classpath:logback-spring-local.xml'
  level:
    root: INFO