server:
  port: 9000
  error:
    include-stacktrace: never

spring:
  jpa:
    generate-ddl: true
    database: MYSQL
    showSql: true
    hibernate:
      ddl-auto: create-drop
    properties.hibernate:
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      format_sql: true
      show_sql: true